Fix The remote certificate is invalid because of errors in the certificate chain: PartialChain.
```
      [SwarmApi]: Server not available. The SSL connection could not be established, see inner exception.
2024-10-29 20:46:35.7255|WARN|Binner.Common.Services.PartService|[SwarmApi]: Server not available. The SSL connection could not be established, see inner exception.|
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
```